### ISSUE TITLE
Configure Cassandra cluster on the cloud - seeds servers

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv-apps#13]
Server seeds are a subset of Casandra nodes which every new nodes go to to get cluster info.
Seeds are contacted when joining the ring,  no other communication with seeds is necessary afterwards
All nodes should have the same seed list.

As such the IP of the seeds server need to be configure in all servers cassandra.yaml: (from [2])

```
seed_provider:
  - class_name: org.apache.cassandra.locator.SimpleSeedProvider
    parameters:
         - seeds:  "110.82.155.0,110.82.155.3"
```

Datastax provides a reflector service.
Each node register to the service with a with a unique cluster id, and after some time, get the details of the other nodes in the cluster.
With the number of nodes in the cluster (from cloud-init), this is enough to set seeds.

Here is where datastax AMI interact with the reflector:
https://github.com/riptano/ComboAMI/blob/2.5/ds2_configure.py#L445
It loops till the number of server in the response match the number of cluster in the service.
The last is a parameter in the cloud-init

[2] http://www.datastax.com/documentation/cassandra/1.2/cassandra/initialize/initializeSingleDS.html
